dependencies:
- name: ccjx-myjx-p1
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: cmyjx_p1
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: myjx_p1
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
